### ISSUE TITLE
i setup postgresql database , i can't login as it shows invalid salt error can you fix that

### ISSUE THREAD

**Issue by timsinasudeep** [hjlarry/flask-shop#27]

**Comment by hjlarry** [comment]
please google for that

**Comment by tharidlynn** [comment]
According to [Official Doc](https://flask-bcrypt.readthedocs.io/en/latest/), this happens when you're using Python 3.


> In Python 3, you need to use decode(‘utf-8’) on generate_password_hash(), like below:
> 
>     pw_hash = bcrypt.generate_password_hash(‘hunter2’).decode(‘utf-8’)



So,  the solution is to add `.decode('utf-8')` to your bcrypt generator function in `account/models.py` and the issue will be fixed.

`self._password = bcrypt.generate_password_hash(value).decode('utf-8')`
